from_time: "2021-01-01T00:00:00Z"
to_time: "2026-01-01T00:00:01Z"
downsample_frequency: "30m"
energy_unit: "MWh"
retry_empty: false
units:
- E_ABERDARE
- T_ABRBO-1
- E_ABRTW-1
- C__PSMAR001
- T_ACHRW-1
- T_AFTOW-1
- 2__AFLEX001
- 2__AFLEX002
- 2__AFLEX003
- 2__AFLEX004
- 2__AFLEX005
- 2__APOWQ001
- 2__ALIME000
- 2__AANGE001
- 2__AANGE002
- 2__ASTAT001
- 2__ASTAT002
- 2__ASTAT003
- 2__ASTAT004
- 2__ASTAT005
- 2__ASTAT006
- 2__ASTAT007
- 2__ASTAT008
- 2__ASTAT009
- 2__ASTAT099
- 2__BLOND003
- 2__BEDGE001
- 2__BFLEX001
- 2__BFLEX002
- 2__BFLEX003
- 2__BFLEX004
- 2__BPOWQ001
- 2__BLIME000
- 2__BANGE001
- 2__BANGE002
- 2__BANGE003
- 2__BSMAR002
- 2__BSMAR003
- 2__BSTAT001
- 2__BSTAT002
- 2__BSTAT003
- 2__BSTAT004
- 2__BSTAT099
- 2__BUKPR001
- 2__CMRCY001
- 2__DLOND001
- 2__DLOND002
- 2__DANGE001
- 2__DSMAE001
- 2__DSMAE002
- 2__DSTAT001
- 2__DSTAT002
- 2__DSTAT003
- 2__DSTAT004
- 2__DSTAT005
- 2__DSTAT006
- 2__DSTAT007
- 2__DSTAT099
- 2__DUKPR001
- V__AFEEL002
- 2__EFLEX001
- 2__EFLEX002
- 2__EFLEX003
- 2__EFLEX004
- 2__ELIME000
- 2__EANGE001
- 2__EANGE002
- 2__ESMAR001
- 2__ESTAT001
- 2__ESTAT002
- 2__ESTAT003
- 2__ESTAT004
- 2__ESTAT005
- 2__ESTAT099
- 2__EUKPR001
- 2__FFLEX001
- 2__FANGE001
- 2__FANGE002
- 2__FSTAT001
- 2__FSTAT002
- 2__FSTAT003
- 2__FSTAT099
- 2__GLOND003
- 2__GLOND004
- 2__GFLEX001
- 2__GFLEX002
- 2__GFLEX003
- 2__GFLEX004
- 2__GFLEX005
- 2__GFLEX006
- 2__GFLEX007
- 2__GFLEX008
- 2__GANGE001
- 2__GANGE002
- 2__GANGE003
- 2__GANGE004
- 2__GSMAE001
- 2__GSTAT001
- 2__GSTAT002
- 2__GSTAT003
- 2__GSTAT004
- 2__GSTAT005
- 2__GSTAT006
- 2__GSTAT007
- 2__GSTAT008
- 2__GSTAT009
- 2__GSTAT010
- 2__GSTAT011
- 2__GSTAT012
- 2__GSTAT013
- 2__GSTAT014
- 2__GSTAT015
- 2__GSTAT016
- 2__GSTAT017
- 2__GSTAT099
- 2__HLOND001
- 2__HLOND002
- 2__HFLEX001
- 2__HANGE001
- 2__HANGE002
- 2__HANGE003
- 2__HANGE004
- 2__HANGE005
- 2__HSMAE001
- 2__HSTAT001
- 2__HSTAT002
- 2__HSTAT003
- 2__HSTAT004
- 2__HSTAT005
- 2__HSTAT006
- 2__HSTAT007
- 2__HSTAT008
- 2__HSTAT099
- 2__JLOND002
- 2__JLOND003
- 2__JANGE001
- 2__JSTAT001
- 2__JSTAT002
- 2__JSTAT003
- 2__JSTAT099
- 2__JUKPR001
- 2__KFLEX001
- 2__KFLEX002
- 2__KANGE001
- 2__KSTAT001
- 2__KSTAT002
- 2__KSTAT003
- 2__KSTAT004
- 2__KSTAT005
- 2__KSTAT006
- 2__KSTAT007
- 2__KSTAT099
- 2__KUKPR001
- 2__LFLEX001
- 2__LANGE001
- 2__LANGE002
- 2__LSTAT001
- 2__LSTAT002
- 2__LSTAT003
- 2__LSTAT004
- 2__LSTAT099
- 2__LUKPR001
- 2__MCMRO002
- 2__MCNDL002
- 2__MFLEX001
- 2__MFLEX002
- 2__MFLEX003
- 2__MFLEX004
- 2__MANGE001
- 2__MANGE002
- 2__MSMAE001
- 2__MSMAE002
- 2__MSTAT001
- 2__MSTAT002
- 2__MSTAT003
- 2__MSTAT004
- 2__MSTAT005
- 2__MSTAT006
- 2__NLOND001
- 2__NLOND002
- 2__NLOND003
- 2__NFLEX001
- 2__NFLEX002
- 2__NFLEX003
- 2__NFLEX004
- 2__NFLEX005
- 2__NFLEX006
- 2__NFLEX007
- 2__NFLEX008
- 2__NFLEX009
- 2__NHPOW001
- 2__NHPOW002
- 2__NANGE001
- 2__NANGE002
- 2__NSMAR002
- 2__NSTAT001
- 2__NSTAT002
- 2__NSTAT003
- 2__NSTAT004
- 2__NSTAT099
- 2__PLOND001
- 2__PFLEX001
- 2__PFLEX002
- V__BJOUL001
- 2__PSMAR001
- 2__LECOT003
- 2__BECOT003
- E_AIRSW-1
- T_AKGLW-2
- T_AKGLW-3
- E_ALCOA-1
- T_ANSUW-1
- E_ARBRB-1
- T_ARCHW-1
- E_ARNKB-1
- E_ARNKB-2
- E_ASHWW-1
- E_ASLVW-1
- E_BABAW-1
- T_BAGE-1
- T_BAGE-2
- E_BARNB-1
- 2__BBPGM001
- T_BDCHW-1
- T_BEATO-1
- T_BEATO-2
- T_BEATO-3
- T_BEATO-4
- T_BEINW-1
- T_BENBW-1
- E_BERKB-1
- E_BETHW-1
- 2__BFSEN005
- T_BHLAW-1
- E_BHOLB-1
- E_BLARW-1
- T_BLHLB-1
- T_BLHLB-2
- T_BLHLB-3
- T_BLHLB-4
- T_BLHLD-1
- T_BLHLD-2
- T_BLHLD-3
- E_BLKPB-1
- T_BLKWW-1
- T_BLLA-1
- T_BLLA-2
- T_BLPFB-1
- E_BNWKW-1
- T_BOWLW-1
- T_BRBEO-1
- T_BRCHS-1
- E_BRDUW-1
- T_BREDB-1
- 2__MCNDL001
- E_BRGG-1
- E_BRIDGWTR
- E_BRNLW-1
- E_BROAB-1
- T_BROCW-1
- E_BROFB-1
- E_BROXB-1
- E_BRYBW-1
- E_BSPHM-1
- E_BTNHL-1
- E_BTUIW-2
- E_BTUIW-3
- E_BURBO
- E_BURGH-1
- E_BURWB-1
- T_BURWS-1
- T_BUSTB-1
- 2__GCMRO001
- 2__NCPPR001
- 2__PSTAT001
- T_CAPNB-1
- T_CARR-1
- T_CARR-2
- M_CAS-BEU01
- M_CAS-CLU01
- M_CAS-CON01
- M_CAS-GAR01
- M_CAS-KIL01
- M_CAS-MOR01
- T_CASKD-1
- E_CATHB-1
- T_CDCL-1
- T_CGTHW-1
- E_CHAPB-1
- E_CHICK-1
- E_CHTRY-1
- E_CLAC-1
- E_CLAYB-1
- E_CLAYB-2
- T_CLDCW-1
- T_CLDNW-1
- E_CLDRW-1
- T_CLDSW-1
- E_CLFLW-1
- T_CLVHS-1
- T_CLVHS-2
- 2__PEDGE003
- E_CNCLW-1
- T_CNQPS-1
- T_CNQPS-2
- T_CNQPS-3
- T_CNQPS-4
- E_CONTB-1
- E_CORB-1
- T_COSO-1
- T_COUWW-1
- T_COVNB-1
- T_COWB-1
- E_COWE1
- E_COWE2
- T_CRDEW-1
- T_CRDEW-2
- T_CREAW-1
- T_CRGHW-1
- E_CRGTW-1
- T_CRMLW-1
- E_CROYD-2
- E_CRSSB-1
- T_CRUA-1
- T_CRUA-2
- T_CRUA-3
- T_CRUA-4
- T_CRUAD-1
- T_CRYRW-2
- T_CRYRW-3
- T_CUMHW-1
- E_CUPAB-1
- E_CWMD-1
- T_DALQW-1
- E_DALSW-1
- T_DAMC-1
- T_DBAWO-1
- T_DBAWO-2
- T_DBAWO-3
- T_DBAWO-4
- T_DBAWO-5
- E_DBFRM-1
- T_DDGNO-1
- T_DDGNO-2
- T_DDGNO-3
- T_DDGNO-4
- E_DERBY-1
- E_DERW-1
- E_DIDC1G
- E_DIDC2G
- E_DIDC3G
- E_DIDC4G
- T_DIDCB5
- T_DIDCB6
- T_DINO-1
- T_DINO-2
- T_DINO-3
- T_DINO-4
- T_DINO-5
- T_DINO-6
- 2__NSMAE001
- T_DNLWW-1
- E_DOLLB-1
- T_DOREW-1
- T_DOREW-2
- T_DOUGW-1
- E_DOWL-1
- E__MDRX001
- T_DRAXX-1
- T_DRAXX-10G
- T_DRAXX-12G
- T_DRAXX-2
- T_DRAXX-3
- T_DRAXX-4
- T_DRAXX-5
- T_DRAXX-6
- T_DRAXX-9G
- T_DRSLW-1
- T_DUNGW-1
- T_DWEXW-1
- T_EAAO-1
- T_EAAO-2
- I_EAG-BRTN1
- I_EAG-ELEC1
- I_EAG-EWIC1
- I_EAG-FRAN1
- I_EAG-GRN1
- I_EAG-IFA2
- I_EAG-MOYL1
- I_EAG-NEMO1
- I_EAG-NSL1
- I_EAG-VKL1
- 2__AAXPO000
- 2__ABGAS000
- 2__AENRD000
- 2__AEOND000
- 2__ARWED000
- 2__AHPOW000
- 2__AHAVE000
- 2__ANATP000
- 2__AMRCY000
- 2__ATGPL000
- 2__ECNDL001
- T_EDINW-1
- T_EECL-1
- 2__BAXPO000
- 2__BBGAS000
- 2__BENRD000
- 2__BEOND000
- 2__BRWED000
- 2__BHPOW000
- 2__BHAVE000
- 2__BLOND000
- 2__BNATP000
- 2__BMRCY000
- 2__BTGPL000
- T_ENDRB-1
- T_ERRO-1
- T_ERRO-2
- T_ERRO-3
- 2__EIMPO002
- T_EWHLW-1
- E_EXETR-2
- T_FARR-1
- T_FARR-2
- T_FALGW-1
- E_FARNB-1
- T_FASN-1
- E_FASN-4
- T_FASN-2
- E_FASN-3
- E_FAWN-1
- 2__FBPGM001
- 2__FBPGM002
- E_FDUN-1
- E_FELL-1
- T_FERRB-1
- T_FERRB-2
- T_FFES-1
- T_FFES-2
- T_FFES-3
- T_FFES-4
- 2__FFSEN005
- 2__FFSEN007
- T_FIDL-1
- T_FIDL-2
- T_FIDL-2G
- T_FIDL-3
- T_FIDL-3G
- T_FIDL-4
- T_FIDLST1
- T_FINL-1
- T_FOYE-1
- T_FOYE-2
- T_FOYED-1
- T_FSDLW-1
- T_GANW-11
- T_GANW-22
- T_GANW-13
- T_GANW-24
- E_GDSTW-1
- E_GFLDW-1
- 2__GFSEN005
- 2__GFSEN006
- E_GLCHW-1
- T_GLEND-1
- T_GLNDO-1
- T_GLNKW-1
- E_GLOFW-1
- 2__JCPPR002
- T_GLWSW-1
- T_GNAPW-1
- T_GNFSW-1
- T_GNFSW-2
- T_GORDW-1
- T_GORDW-2
- E_GOSHS-1
- T_GRAI-6
- T_GRAI-7
- T_GRAI-8
- T_GRAI1G
- T_GRAI4G
- T_GRAISC-1
- T_GRAISC-2
- E_GRCRB-1
- T_GRGBW-1
- T_GRGBW-2
- T_GRGBW-3
- E_GRGRW-1
- T_GRIFW-1
- T_GRIFW-2
- T_GRMO-1
- 2__GSMAE003
- E_GYAR-1
- T_GYMR-15
- T_GYMR-17
- T_GYMR-26
- T_GYMR-28
- T_HADHW-1
- T_HAGHW-2
- T_HAHAW-1
- T_HALSW-1
- E_HAWKB-1
- E_HBHDW-1
- T_HEYM11
- T_HEYM12
- T_HEYM27
- T_HEYM28
- T_HINB-D
- T_HIRWN-1
- E_HLGLW-1
- E_HLTWW-1
- T_HMGTO-1
- T_HMGTO-2
- T_HOWAO-1
- T_HOWAO-2
- T_HOWAO-3
- T_HOWBO-1
- T_HOWBO-2
- T_HOWBO-3
- E_HRHLW-1
- T_HRSTB-1
- T_HRSTW-1
- T_HRTL-1
- T_HRTL-2
- 2__HIMPO002
- T_HUMR-1
- T_HUMR-2
- T_HUMRD-1
- T_HUNB-7
- T_HUNB-8
- E_HYWDW-1
- I_I2G-ALEU1
- I_I2G-ALIP1
- I_I2G-ALPE1
- I_I2G-ARON1
- I_I2G-AROS1
- I_I2G-ATLS1
- I_I2G-AXPO1
- I_I2G-BAYW1
- I_I2G-BDEN1
- I_I2G-BKWE1
- I_I2G-BNPS1
- I_I2G-BPGM1
- I_I2G-CACM1
- I_I2G-CBST1
- I_I2G-CCME1
- I_I2G-CENT1
- I_I2G-CETL1
- I_I2G-CEZC1
- I_I2G-CFPE1
- I_I2G-CNGS1
- I_I2G-CNRE1
- I_I2G-COMM1
- I_I2G-CONS1
- I_I2G-CONV1
- I_I2G-COPN1
- I_I2G-CURR1
- I_I2G-DARE1
- I_I2G-DMCC1
- I_I2G-DSKC1
- I_I2G-DUEN1
- I_I2G-DUGE1
- I_I2G-DVAL1
- I_I2G-DVTD1
- I_I2G-EDFT1
- I_I2G-EDMK1
- I_I2G-ELEE1
- I_I2G-ELTR1
- I_I2G-ENBW1
- I_I2G-ENKI1
- I_I2G-ENSC1
- I_I2G-ENSP1
- I_I2G-ENTC1
- I_I2G-EPCO1
- I_I2G-EWII1
- I_I2G-EXXO1
- I_I2G-EZCO1
- I_I2G-EZPD1
- I_I2G-FLEX1
- I_I2G-GASE1
- I_I2G-GAZP1
- I_I2G-GENI1
- I_I2G-GLEN1
- I_I2G-GRMC1
- I_I2G-GRMT1
- I_I2G-HART1
- I_I2G-HELI1
- I_I2G-IBES1
- I_I2G-IDCT1
- I_I2G-INCM1
- I_I2G-MCRA1
- I_I2G-MFTE1
- I_I2G-MQBN1
- I_I2G-NDPL1
- I_I2G-NEAS1
- I_I2G-NEHO1
- I_I2G-NITR1
- I_I2G-NORL1
- I_I2G-NTPL1
- I_I2G-NVAL1
- I_I2G-OMPX1
- I_I2G-OPMX1
- I_I2G-OUTL1
- I_I2G-PEAK1
- I_I2G-PETC1
- I_I2G-PLAN1
- I_I2G-PREP1
- I_I2G-PWMR1
- I_I2G-QTPT1
- I_I2G-QUAR1
- I_I2G-QUEN1
- I_I2G-RESP1
- I_I2G-RISQ1
- I_I2G-RWES1
- I_I2G-SETL1
- I_I2G-SIRI1
- I_I2G-STAT1
- I_I2G-STGS1
- I_I2G-TGPL1
- I_I2G-TRFD1
- I_I2G-TRFG1
- I_I2G-TRGY1
- I_I2G-TRLS1
- I_I2G-TRSI1
- I_I2G-VOLT1
- I_I2G-VSAL1
- I_I2G-VTET1
- I_I2G-WOLF1
- I_I2G-XNON1
- I_IBG-AARH1
- I_IBG-ALIP1
- I_IBG-ALPE1
- I_IBG-ARON1
- I_IBG-AROS1
- I_IBG-ATLS1
- I_IBG-BDEN1
- I_IBG-BKWE1
- I_IBG-BPGE1
- I_IBG-BRTN1
- I_IBG-CACM1
- I_IBG-CBST1
- I_IBG-CCME1
- I_IBG-CENT1
- I_IBG-CETA1
- I_IBG-CEZC1
- I_IBG-CFPE1
- I_IBG-CGML1
- I_IBG-CNGS1
- I_IBG-COMM1
- I_IBG-CONS1
- I_IBG-CONV1
- I_IBG-COPN1
- I_IBG-CURR1
- I_IBG-DARE1
- I_IBG-DMCC1
- I_IBG-DNGN1
- I_IBG-DSKC1
- I_IBG-DUFE1
- I_IBG-DVAL1
- I_IBG-DVTD1
- I_IBG-EDFT1
- I_IBG-EDMK1
- I_IBG-EGLE1
- I_IBG-ELEE1
- I_IBG-ELTR1
- I_IBG-ENEL1
- I_IBG-ENET1
- I_IBG-ENGM1
- I_IBG-ENSP1
- I_IBG-ENTC1
- I_IBG-EOET1
- I_IBG-EPCO1
- I_IBG-ERVA1
- I_IBG-EWII1
- I_IBG-EZC01
- I_IBG-EZCO1
- I_IBG-EZPD1
- I_IBG-FLEX1
- I_IBG-FPCD1
- I_IBG-GAZP1
- I_IBG-GENI1
- I_IBG-GLEN1
- I_IBG-GRMC1
- I_IBG-GRMT1
- I_IBG-GRNC1
- I_IBG-HART1
- I_IBG-HELI1
- I_IBG-IBES1
- I_IBG-IDCE1
- I_IBG-IDCT1
- I_IBG-INCM1
- I_IBG-KCST1
- I_IBG-LTFD1
- I_IBG-MCRA1
- I_IBG-MFTE1
- I_IBG-MONL1
- I_IBG-NEAS1
- I_IBG-NEHO1
- I_IBG-NITR1
- I_IBG-NORL1
- I_IBG-NTPL1
- I_IBG-OMPX1
- I_IBG-OPMX1
- I_IBG-OUTL1
- I_IBG-PETC1
- I_IBG-PTRS1
- I_IBG-PWMR1
- I_IBG-PZEM1
- I_IBG-QTPT1
- I_IBG-QUAR1
- I_IBG-QUEN1
- I_IBG-RESP1
- I_IBG-RISQ1
- I_IBG-RWES1
- I_IBG-SEAG1
- I_IBG-SETL1
- I_IBG-SIRI1
- I_IBG-STAT1
- I_IBG-STGS1
- I_IBG-TGPL1
- I_IBG-TRFD1
- I_IBG-TRFG1
- I_IBG-TRLS1
- I_IBG-VETR1
- I_IBG-VOLT1
- I_IBG-VSAL1
- I_IBG-VTUS1
- I_IBG-XNON1
- I_IEG-ELEC1
- I_IEG-EWIC1
- I_IEG-FRAN1
- I_IEG-GRN1
- I_IEG-IFA2
- I_IEG-MOYL1
- I_IEG-NSL1
- I_IEG-VKL1
- I_IFG-ACCE1
- I_IFG-ALEU1
- I_IFG-ALIP1
- I_IFG-ALPE1
- I_IFG-ARON1
- I_IFG-AROS1
- I_IFG-ATLS1
- I_IFG-BAYW1
- I_IFG-BDEN1
- I_IFG-BKWE1
- I_IFG-BNPS1
- I_IFG-BPGE1
- I_IFG-CACM1
- I_IFG-CBST1
- I_IFG-CCME1
- I_IFG-CETL1
- I_IFG-CEZC1
- I_IFG-CFPE1
- I_IFG-CGML1
- I_IFG-CNGS1
- I_IFG-CNRE1
- I_IFG-COMM1
- I_IFG-CONS1
- I_IFG-CONV1
- I_IFG-COPN1
- I_IFG-CURR1
- I_IFG-DARE1
- I_IFG-DMCC1
- I_IFG-DNGN1
- I_IFG-DSKC1
- I_IFG-DUEN1
- I_IFG-DUFE1
- I_IFG-DVAL1
- I_IFG-DVTD1
- I_IFG-ECCA1
- I_IFG-EDFT1
- I_IFG-EDMK1
- I_IFG-EGLE1
- I_IFG-ELEE1
- I_IFG-ELTR1
- I_IFG-ENBW1
- I_IFG-ENEL1
- I_IFG-ENET1
- I_IFG-ENKI1
- I_IFG-ENSC1
- I_IFG-ENSP1
- I_IFG-ENTC1
- I_IFG-ENVM1
- I_IFG-EOET1
- I_IFG-EPCO1
- I_IFG-ERVA1
- I_IFG-EWII1
- I_IFG-EXXO1
- I_IFG-EZCO1
- I_IFG-EZPD1
- I_IFG-FLEX1
- I_IFG-FPCD1
- I_IFG-GASE1
- I_IFG-GAZP1
- I_IFG-GDFE1
- I_IFG-GENI1
- I_IFG-GLEN1
- I_IFG-GRMC1
- I_IFG-GRMT1
- I_IFG-HART1
- I_IFG-HELI1
- I_IFG-IBES1
- I_IFG-IDCT1
- I_IFG-INCM1
- I_IFG-KCST1
- I_IFG-LTFD1
- I_IFG-MCRA1
- I_IFG-MFTE1
- I_IFG-MQBN1
- I_IFG-NEAS1
- I_IFG-NEHO1
- I_IFG-NITR1
- I_IFG-NORL1
- I_IFG-NSDQ1
- I_IFG-NTPL1
- I_IFG-NVAL1
- I_IFG-OMPX1
- I_IFG-OPMX1
- I_IFG-OUTL1
- I_IFG-PEAK1
- I_IFG-PETC1
- I_IFG-PLAN1
- I_IFG-PTRS1
- I_IFG-PWMR1
- I_IFG-QTPT1
- I_IFG-QUAR1
- I_IFG-QUEN1
- I_IFG-RESP1
- I_IFG-RISQ1
- I_IFG-RWES1
- I_IFG-SETL1
- I_IFG-SIRI1
- I_IFG-SPEM1
- I_IFG-STAT1
- I_IFG-STGS1
- I_IFG-TFEE1
- I_IFG-TRFD1
- I_IFG-TRFG1
- I_IFG-TRGY1
- I_IFG-TRLS1
- I_IFG-TRSI1
- I_IFG-VOLT1
- I_IFG-VSAL1
- I_IFG-VTFS1
- I_IFG-WOLF1
- I_IFG-XNON1
- I_IGG-STAT1
- I_IIG-AXPO1
- I_IIG-BGSE1
- I_IIG-BRKF1
- I_IIG-DSKC1
- I_IIG-ELTR1
- I_IIG-ENGI1
- I_IIG-ERVA1
- I_IIG-ESBI1
- I_IIG-ESBI2
- I_IIG-INCM1
- I_IIG-LTFD1
- I_IIG-NSEN1
- I_IIG-RWES1
- I_IIG-SEEL1
- I_IIG-STAT1
- I_IIG-VAYU1
- I_IIG-VESL1
- I_ILG-ALIP1
- I_ILG-ALPE1
- I_ILG-ARON1
- I_ILG-AROS1
- I_ILG-ATLS1
- I_ILG-BAYW1
- I_ILG-BKWE1
- I_ILG-BPGM1
- I_ILG-CACM1
- I_ILG-CBST1
- I_ILG-CCME1
- I_ILG-CENT1
- I_ILG-CETL1
- I_ILG-CEZC1
- I_ILG-CFPE1
- I_ILG-COMM1
- I_ILG-CONS1
- I_ILG-COPN1
- I_ILG-CURR1
- I_ILG-DARE1
- I_ILG-DMCC1
- I_ILG-DSKC1
- I_ILG-DUEN1
- I_ILG-DUFE1
- I_ILG-DVAL1
- I_ILG-DVTD1
- I_ILG-EDFT1
- I_ILG-EDMK1
- I_ILG-ELTR1
- I_ILG-ENBW1
- I_ILG-ENGM1
- I_ILG-ENSC1
- I_ILG-ENTC1
- I_ILG-EPCO1
- I_ILG-EWII1
- I_ILG-EXXO1
- I_ILG-EZCO1
- I_ILG-EZPD1
- I_ILG-FLEX1
- I_ILG-GENI1
- I_ILG-GLEN1
- I_ILG-GNER1
- I_ILG-GRMC1
- I_ILG-HART1
- I_ILG-HELI1
- I_ILG-INCM1
- I_ILG-MCRA1
- I_ILG-MFTE1
- I_ILG-NDPL1
- I_ILG-NEAS1
- I_ILG-NEHO1
- I_ILG-NITR1
- I_ILG-NORL1
- I_ILG-NTPL1
- I_ILG-NWAT1
- I_ILG-OPMX1
- I_ILG-OUTL1
- I_ILG-PEAK1
- I_ILG-PETC1
- I_ILG-PREP1
- I_ILG-PWMR1
- I_ILG-QUAR1
- I_ILG-RESP1
- I_ILG-RISQ1
- I_ILG-RWES1
- I_ILG-SEFE1
- I_ILG-SETL1
- I_ILG-SIRI1
- I_ILG-STGS1
- I_ILG-TGPL1
- I_ILG-TRFD1
- I_ILG-TRFG1
- I_ILG-TRLS1
- I_ILG-VOLT1
- I_ILG-VSAL1
- I_ILG-VTFS1
- I_ILG-XNON1
- E_ILMEB-1
- I_IMG-AXPO1
- I_IMG-BGSE1
- I_IMG-BRKF1
- I_IMG-DSKC1
- I_IMG-ELTR1
- I_IMG-ENGI1
- I_IMG-ERVA1
- I_IMG-ESBE1
- I_IMG-ESBI1
- I_IMG-INCM1
- I_IMG-LTFD1
- I_IMG-NSEN1
- I_IMG-RWES1
- I_IMG-SEEL1
- I_IMG-SPEM1
- I_IMG-STAT1
- T_INDQ-1
- I_ING-ALIP1
- I_ING-ALPE1
- I_ING-ARON1
- I_ING-AROS1
- I_ING-ATLS1
- I_ING-AXPO1
- I_ING-BDEN1
- I_ING-BKWE1
- I_ING-BPGM1
- I_ING-CACM1
- I_ING-CBST1
- I_ING-CCME1
- I_ING-CENT1
- I_ING-CETA1
- I_ING-CEZC1
- I_ING-CFPE1
- I_ING-CNGS1
- I_ING-COMM1
- I_ING-CONS1
- I_ING-CONV1
- I_ING-COPN1
- I_ING-DARE1
- I_ING-DMCC1
- I_ING-DSKC1
- I_ING-DUFE1
- I_ING-DVAL1
- I_ING-EDFT1
- I_ING-EDMK1
- I_ING-ELEE1
- I_ING-ELTR1
- I_ING-ENET1
- I_ING-ENTC1
- I_ING-EPCO1
- I_ING-EWII1
- I_ING-EZCO1
- I_ING-FLEX1
- I_ING-GASE1
- I_ING-GAZP1
- I_ING-GENI1
- I_ING-GLEN1
- I_ING-GRMC1
- I_ING-HART1
- I_ING-HELI1
- I_ING-IDCE1
- I_ING-IDCT1
- I_ING-INCM1
- I_ING-KCST1
- I_ING-LMUS1
- I_ING-MCRA1
- I_ING-MFTE1
- I_ING-NDPL1
- I_ING-NEAS1
- I_ING-NEHO1
- I_ING-NEMO1
- I_ING-NITR1
- I_ING-NORL1
- I_ING-NTPL1
- I_ING-OMPX1
- I_ING-OPMX1
- I_ING-OUTL1
- I_ING-PETC1
- I_ING-PWMR1
- I_ING-QUEN1
- I_ING-RESP1
- I_ING-RISQ1
- I_ING-RWES1
- I_ING-SECF1
- I_ING-SETL1
- I_ING-SIRI1
- I_ING-STAT1
- I_ING-STGS1
- I_ING-TGPL1
- I_ING-TRFD1
- I_ING-TRFG1
- I_ING-TRLS1
- I_ING-VOLT1
- I_ING-VSAL1
- I_ING-VTET1
- I_ING-XNON1
- I_ISG-DMCC1
- I_ISG-NDPL1
- I_IVG-AARH1
- I_IVG-AENG1
- I_IVG-ALIP1
- I_IVG-ALPE1
- I_IVG-AROS1
- I_IVG-ATLS1
- I_IVG-BDEN1
- I_IVG-CACM1
- I_IVG-CONV1
- I_IVG-COPN1
- I_IVG-CURR1
- I_IVG-DARE1
- I_IVG-DSKC1
- I_IVG-DVAL1
- I_IVG-EDFT1
- I_IVG-EDMK1
- I_IVG-EENG1
- I_IVG-ELTR1
- I_IVG-ENSC1
- I_IVG-EWII1
- I_IVG-EZCO1
- I_IVG-GRDC1
- I_IVG-GRMC1
- I_IVG-GRMT1
- I_IVG-HART1
- I_IVG-HELI1
- I_IVG-IDCE1
- I_IVG-IDCT1
- I_IVG-INCM1
- I_IVG-KVAS1
- I_IVG-LYSE1
- I_IVG-MFTE1
- I_IVG-NEAS1
- I_IVG-NEHO1
- I_IVG-NEXT1
- I_IVG-NITR1
- I_IVG-NORL1
- I_IVG-NTPL1
- I_IVG-OPMX1
- I_IVG-OUTL1
- I_IVG-PETC1
- I_IVG-PWMR1
- I_IVG-QTPT1
- I_IVG-QUEN1
- I_IVG-RESP1
- I_IVG-RWES1
- I_IVG-SEFE1
- I_IVG-STAT1
- I_IVG-STGS1
- I_IVG-TGPL1
- I_IVG-TRAS1
- I_IVG-TRLS1
- I_IVG-VOLT1
- I_IVG-VSAL1
- I_IVG-VTFS1
- I_IVG-WOLF1
- E_JAMBB-1
- E_JAMBB-2
- T_JGPR-1
- T_KEAD-1
- T_KEAD-2
- T_KEADGT-3
- T_KEMB-1
- T_KENNW-1
- E_KHLLW-1
- T_KILBW-1
- T_KILLPG-1
- T_KILLPG-2
- T_KILNS-1
- E_KINCW-1
- T_KLGLW-1
- E_KLYN-A-1
- T_KPMRW-1
- T_KTHLW-1
- T_KYPEW-1
- T_LAGA-1
- T_LARKB-1
- T_LARKS-1
- T_LARYW-1
- T_LARYW-2
- T_LARYW-3
- T_LARYW-4
- T_LBAR-1
- T_LBAR-1G
- E_LCHWT-1
- 2__LRWED001
- T_LCLTW-1
- 2__PMARB001
- 2__LFSEN200
- T_LIMKW-1
- E_LITRB-1
- T_LKSDB-1
- T_LNCSW-1
- T_LNCSW-2
- E_LYNE1
- E_LYNE2
- E_LYNE3
- 2__CEOND000
- 2__CRWED000
- 2__CNATP000
- 2__CTGPL000
- T_LRDSC-1
- T_LRDSC-2
- E_LSTWY-1
- V__HFEEL002
- E_MANXENR-1
- E_MARK-1
- 2__PSTAT002
- E_MDLWH-1
- T_MEADD-1
- T_MEDP-1
- 2__EAXPO000
- 2__EBGAS000
- 2__EEOND000
- 2__ERWED000
- 2__EHPOW000
- 2__ENATP000
- 2__EOVOE000
- 2__ETGPL000
- T_MIDMW-1
- T_MILWW-1
- E_MINSW-1
- T_MKFRB-1
- T_MKHLW-1
- 2__DAXPO000
- 2__DBGAS000
- 2__DBIZZ000
- 2__DEDFE000
- 2__DEOND000
- 2__DRWED000
- 2__DHPOW000
- 2__DHAVE000
- 2__DMANW000
- 2__DNATP000
- 2__DMRCY000
- 2__DOVOE000
- 2__DSPOW000
- 2__DTGPL000
- 2__DTILL000
- E_MORFL-1
- T_EXMOSSD-1
- T_MOWEO-1
- T_MOWEO-2
- T_MOWEO-3
- T_MOWWO-1
- T_MOWWO-2
- T_MOWWO-3
- T_MOWWO-4
- E_MOYEW-1
- T_MRWD-1
- T_MYGPW-1
- T_NANT-1
- 2__FAXPO000
- 2__FBGAS000
- 2__FENRD000
- 2__FEOND000
- 2__FRWED000
- 2__FHPOW000
- 2__FHAVE000
- 2__FNATP000
- 2__FMRCY000
- 2__FOVOE000
- 2__FTGPL000
- E_NEWPB-1
- E_NEWTB-1
- 2__NFSEN007
- T_NLSTB-1
- T_NNGAO-1
- T_NNGAO-2
- 2__NNATP001
- T_NOKYW-1
- T_NOKYW-2
- 2__PIMPO000
- 2__PAXPO000
- 2__PBGAS000
- 2__PBIZZ000
- 2__PEDFE000
- 2__PENRD000
- 2__PEOND000
- 2__PRWED000
- 2__PHPOW000
- 2__PHAVE000
- 2__PLOND000
- 2__PNATP000
- 2__PMRCY000
- 2__POVOE000
- 2__PSPOW000
- 2__PTGPL000
- 2__PTILL000
- E_NTAWB-1
- T_NTRVB-1
- T_NURSB-1
- 2__GAXPO000
- 2__GBGAS000
- 2__GEOND000
- 2__GRWED000
- 2__GHPOW000
- 2__GHAVE000
- 2__GNATP000
- 2__GMRCY000
- 2__GOVOE000
- 2__GSPOW000
- 2__GTGPL000
- T_OCHLB-1
- E_OLDHB-1
- T_OMNDW-1
- T_PARHD-1
- 2__PENEC002
- T_PEHE-1
- T_PEMB-11
- T_PEMB-21
- T_PEMB-31
- T_PEMB-41
- T_PEMB-51
- E_PETEM1
- E_PETEM3
- T_PGBIW-1
- E_PGBRKL
- E_PGBARY
- E_PGEXTR
- E_PGFARE
- E_PGHVNT
- E_PGLLAN
- E_PGSOUT
- E_PIBUW-1
- E_PILLB-1
- E_PILLB-2
- T_PINFB-1
- T_PINFB-2
- T_PINFB-3
- T_PINFB-4
- E_PLYRK-1
- T_PNYCB-1
- T_PNYCW-1
- E_POTES-1
- E_RAKE-1
- E_RASSP-1
- T_RATSGT-2
- T_RATSGT-4
- T_RAVED-1
- T_RCBKO-1
- T_RCBKO-2
- E_RDFRB-1
- E_RDFRD-1
- E_RDSCR-1
- E_RHEI-1
- T_RICHB-1
- T_RICHB-2
- T_RMPNO-1
- T_RMPNO-2
- E_ROARB-1
- T_ROCK-1
- E_ROOSB-1
- 2__PENEC001
- T_RREW-1
- T_RRWW-1
- 2__FRWED001
- 2__PEDGE004
- T_RTHSC-1
- T_RYHPS-1
- T_SAKNW-1
- T_SANQW-1
- T_SCCL-1
- T_SCCL-2
- T_SCCL-3
- T_SEAB-1
- T_SEAB-2
- 2__JAXPO000
- 2__JBGAS000
- 2__JENRD000
- 2__JEOND000
- 2__JRWED000
- 2__JHAVE000
- 2__JNATP000
- 2__JMRCY000
- 2__JTGPL000
- 2__JVETS000
- T_SEEL-1
- E_SEVINGTN
- T_SGRWO-1
- T_SGRWO-2
- T_SGRWO-3
- T_SGRWO-4
- T_SGRWO-5
- T_SGRWO-6
- T_SHBA-1
- T_SHBA-2
- E_SHILB-1
- E_SHOS-1
- T_SHRSW-1
- T_SHRSW-2
- T_SIZB-1
- T_SIZB-2
- E_SKELB-1
- M_SLOY-1
- T_SLOY-2
- T_SLOY-3
- M_SLOY-4
- T_SOKYW-1
- E_SOLUTIA
- T_SPLN-1
- 2__NIMPO000
- 2__NAXPO000
- 2__NBGAS000
- 2__NENRD000
- 2__NEOND000
- 2__NRWED000
- 2__NHPOW000
- 2__NHAVE000
- 2__NLOND000
- 2__NNATP000
- 2__NMRCY000
- 2__NSPOW000
- 2__NTGPL000
- E_STALB-1
- T_STAY-1
- T_STAY-2
- T_STAY-3
- T_STAY-4
- 2__HAXPO000
- 2__HBGAS000
- 2__HENRD000
- 2__HEOND000
- 2__HRWED000
- 2__HHPOW000
- 2__HHAVE000
- 2__HNATP000
- 2__HMRCY000
- 2__HTGPL000
- T_STLGW-1
- T_STLGW-2
- T_STLGW-3
- T_STRNW-1
- E_SUDME-1
- T_SUNDB-1
- T_SUTB-1
- T_SUTBS-1
- T_SVRP-10
- T_SVRP-20
- 2__KAXPO000
- 2__KBGAS000
- 2__KENRD000
- 2__KEOND000
- 2__KRWED000
- 2__KHPOW000
- 2__KHAVE000
- 2__KLOND000
- 2__KNATP000
- 2__KMRCY000
- 2__KOVOE000
- 2__KTGPL000
- 2__KUKPR000
- E_SWBKW-1
- E_SWDNB-1
- 2__MCMRO003
- 2__LAXPO000
- 2__LBGAS000
- 2__LENRD000
- 2__LEOND000
- 2__LRWED000
- 2__LHAVE000
- 2__LLOND000
- 2__LNATP000
- 2__LMRCY000
- 2__LOVOE000
- 2__LSWEB000
- 2__LTGPL000
- T_SZJNB-1
- T_FERGD-1
- T_FERGD-2
- 2__PSMAE003
- E_TAYL2G
- E_TAYL3G
- T_TDBNW-1
- E_TDRVE-1
- T_TEBWB-1
- T_TEBWS-1
- E_THMRB-1
- T_THNTO-1
- T_THNTO-2
- E_THRNL-1
- T_THURB-1
- T_THURB-2
- T_THURB-3
- E_TGP1
- T_TKNEW-1
- T_TKNWW-1
- E_TLYMW-1
- C__PSTAT011
- T_TODSD-1
- E_TOLLB-1
- T_TORN-1
- T_TORN-2
- E_TORQB-1
- E_TRFPK-1
- T_TRLGW-1
- T__KYELT003
- T_TSREP-1
- E_TULWW-1
- E_TULWW-2
- T_TWSHW-1
- T_TYLNB-1
- T_TYLNS-1
- T_USKM-13
- E_VKING-2
- T_VKNGW-1
- T_VKNGW-2
- T_VKNGW-3
- T_VKNGW-4
- T_WBUGT-1
- T_WBUGT-4
- T_WBUPS-1
- T_WBUPS-2
- T_WBUPS-3
- T_WBUPS-4
- T_WBURB-1
- T_WBURB-2
- T_WBURB-3
- T_WBURB-41
- T_WBURB-43
- T_WDNSO-1
- T_WDNSO-2
- T_WDRGW-1
- T_WHIHW-1
- T_WHILW-1
- T_WHILW-2
- T_WHLWB-1
- E_WHTBB-1
- T_WILCT-1
- T_WISHB-1
- T_WISHD-1
- T_WISTW-2
- T_WLNYO-2
- T_WLNYO-3
- T_WLNYO-4
- T_WLNYW-1
- T_WTMSO-1
- E_WTRLN-1
- 2__GCMRO002
- 2__MIMPO000
- 2__MAXPO000
- 2__MBGAS000
- 2__MENRD000
- 2__MEOND000
- 2__MRWED000
- 2__MHPOW000
- 2__MHAVE000
- 2__MNATP000
- 2__MMRCY000
- 2__MOVOE000
- 2__MTGPL000
