from_time: "2025-01-01T00:00:00Z"
to_time: "2025-10-29T00:00:00Z"
downsample_frequency: "7d"
units:
- T_ACHRW-1
- T_AFTOW-1
- T_AKGLW-3
- T_AKGLW-2
- E_AIRSW-1
- T_ANSUW-1
- E_ASHWW-1
- T_ARCHW-1
- E_ASLVW-1
- E_ABRTW-1
- E_BRNLW-1
- T_BDCHW-1
- E_BABAW-1
- T_BOWLW-1
- T_BEATO-2
- T_BEATO-1
- T_BEATO-4
- T_BEATO-3
- E_BETHW-1
- E_BTUIW-3
- E_BTUIW-2
- T_BEINW-1
- E_BRYBW-1
- 2__PSTAT002
- T_BHLAW-1
- T_BLLA-1
- T_BLLA-2
- T_BLKWW-1
- E_BLARW-1
- E_BRDUW-1
- T_NOKYW-2
- T_NOKYW-1
- T_WISTW-2
- T_BROCW-1
- T_BRBEO-1
- E_BURBO
- E_BNWKW-1
- 2__PEDGE003
- T_CRGHW-1
- 2__PSMAE001
- T_LNCSW-1
- T_LNCSW-2
- E_CLFLW-1
- E_CLAC-1
- E_CLDRW-1
- T_CLDCW-1
- T_CLDSW-1
- T_CLDNW-1
- E_CNCLW-1
- T_CGTHW-1
- T_CRMLW-1
- T_CDCL-1
- T_COUWW-1
- E_CRGTW-1
- T_CREAW-1
- T_CRDEW-2
- T_CRDEW-1
- T_CRYRW-3
- T_CRYRW-2
- T_CUMHW-1
- T_DALQW-1
- E_DALSW-1
- T_DRSLW-1
- T_DBAWO-5
- T_DBAWO-3
- T_DBAWO-4
- T_DBAWO-2
- T_DBAWO-1
- T_DOREW-1
- T_DOREW-2
- T_DOUGW-1
- T_DDGNO-4
- T_DDGNO-1
- T_DDGNO-2
- T_DDGNO-3
- T_DNLWW-1
- T_DUNGW-1
- T_EAAO-2
- T_EAAO-1
- E_TULWW-2
- T_EDINW-1
- T_ABRBO-1
- T_EWHLW-1
- T_FALGW-1
- T_FARR-1
- T_FARR-2
- T_FSDLW-1
- T_GLWSW-1
- T_GANW-13
- T_GANW-11
- T_GANW-24
- T_GANW-22
- T_GNAPW-1
- T_GLNKW-1
- E_GLCHW-1
- E_GLOFW-1
- E_GFLDW-1
- T_GORDW-1
- T_GORDW-2
- E_GDSTW-1
- T_GRGBW-2
- T_GRGBW-1
- T_GRGBW-3
- E_GRGRW-1
- T_GRIFW-2
- T_GRIFW-1
- T_GNFSW-1
- T_GNFSW-2
- T_GYMR-26
- T_GYMR-15
- T_GYMR-17
- T_GYMR-28
- T_HADHW-1
- T_HAHAW-1
- T_HALSW-1
- E_HBHDW-1
- E_HRHLW-1
- T_HRSTW-1
- T_HEYM12
- T_HEYM11
- E_HLGLW-1
- E_HLTWW-1
- T_HOWAO-1
- T_HOWAO-3
- T_HOWAO-2
- T_HOWBO-3
- T_HOWBO-2
- T_HOWBO-1
- T_HMGTO-1
- T_HMGTO-2
- E_HYWDW-1
- T_KEADGT-3
- T_KEAD-2
- T_KEAD-1
- T_KTHLW-1
- T_KENNW-1
- T_KILBW-1
- T_KLGLW-1
- E_KINCW-1
- E_KHLLW-1
- T_KPMRW-1
- T_KYPEW-1
- T_LIMKW-1
- T_LCLTW-1
- T_LARYW-1
- T_LARYW-3
- T_LARYW-4
- T_LARYW-2
- T_MKHLW-1
- T_MIDMW-1
- T_MILWW-1
- T_MYGPW-1
- E_MINSW-1
- T_MOWEO-1
- T_MOWEO-2
- T_MOWEO-3
- T_MOWWO-3
- T_MOWWO-4
- T_MOWWO-1
- T_MOWWO-2
- E_MOYEW-1
- T_NNGAO-1
- T_NNGAO-2
- T_OMNDW-1
- 2__PENEC002
- T_PNYCW-1
- E_PIBUW-1
- T_PGBIW-1
- T_HEYM28
- T_HEYM2-D
- T_RCBKO-2
- T_RCBKO-1
- T_RMPNO-2
- T_RMPNO-1
- E_RHEI-1
- T_RRWW-1
- T_RREW-1
- 2__PEDGE004
- 2__PSTAT001
- 2__PENEC001
- T_SAKNW-1
- T_SANQW-1
- T_SGRWO-6
- T_SGRWO-5
- T_SGRWO-3
- T_SGRWO-1
- T_SGRWO-4
- T_SGRWO-2
- T_SHRSW-1
- T_SHRSW-2
- E_SOLUTIA
- E_SWBKW-1
- T_SOKYW-1
- T_STRNW-1
- T_STLGW-2
- T_STLGW-3
- T_STLGW-1
- T_THNTO-2
- T_THNTO-1
- T_TDBNW-1
- C__PSTAT011
- T_TRLGW-1
- T_TKNEW-1
- T_TKNWW-1
- E_TULWW-1
- E_TLYMW-1
- T_TWSHW-1
- T_VKNGW-2
- T_VKNGW-3
- T_VKNGW-4
- T_VKNGW-1
- T_WLNYW-1
- T_WLNYO-2
- T_WLNYO-3
- T_WLNYO-4
- T_WDNSO-2
- T_WDNSO-1
- T_WTMSO-1
- T_WHILW-1
- T_WHILW-2
- T_WHIHW-1
- T_WILCT-1
- T_WDRGW-1